name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble
    strategy:
      fail-fast: false
      matrix:
        framework: [alpine, angular, lit, nuxt, preact, react, solid, svelte, tanstack, vinext, vue]
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Configure PNPM store
        run: pnpm config set store-dir ~/.pnpm-store/v10

      - name: Restore PNPM store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store/v10
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --prefer-offline

      - name: Test vite 7
        if: matrix.framework != 'nuxt' && matrix.framework != 'tanstack' && matrix.framework != 'react'
        uses: ./.github/actions/test-vite
        with:
          vite-version: "7"
          framework: ${{ matrix.framework }}

      - name: Test vite 8
        if: matrix.framework != 'angular'
        uses: ./.github/actions/test-vite
        with:
          vite-version: "8"
          framework: ${{ matrix.framework }}

      - name: Test nuxt
        if: matrix.framework == 'nuxt'
        uses: ./.github/actions/test-vite
        with:
          framework: nuxt
